const espContent = {
  "navbar1": "Aprende",
  "navbar2": "Explora",
  "navbar3": "ADQUIRE AGOD ",
  "homesection2HeadingWelcome":"Bienvenido a",
  "homesection2Heading": "AGOD ECOSISTEMA",
  "homesection2SlogHeading": "Desbloquea El Máximo @@ Potencial Blockchain",
  "homesection3Text": "Integrando los mejores servicios de blockchain para ofrecer a los usuarios e inversores oportunidades de inversión de primer nivel con grandes recompensas.",
  "homesectionList1": "LISTA DE ESPERA",
  "homesectionList2": "COMPRAR",
  "homesectionPara1": "Ecosistema de Plataformas Interconectadas.",
  "homesectionPara2": "Beneficios Para la Comunidad",
  "homesectionPara3": "Oportunidades de Inversion del Mundo Real.",
  "homesectionPara4": "Impulsado por el Token AGOD.",
  "homesectionCommunity": "Suministro Limitado a 100 M",
  "homecommunityPara": "Suministro inicial de 200 millones, @@ logrando mayor valor con un mecanismo @@ deflacionario a través de @@ un sistema de recompra y quema de tokens.",
  "homesectionUnivers": "Mecanismo de @@ Recompensa",
  "homeuniversPara": "Mecanismo de recompensas compartidas @@ con el crecimiento del ecosistema. @@ Obten descuentos y bonificaciones al @@ holdear AGOD y califica para compartir el @@ 20% de los ingresos generados por @@ tarifas.",
  "homeheading": "APLICACIONES &nbsp;&nbsp;&nbsp; FINANCIERAS &nbsp;&nbsp;&nbsp; DESCENTRALIZADAS",
  "homesectionEcosystem": "EL CORAZÓN @@ DEL ECOSISTEMA",
  "homesection16Heading": "DREAMHUB - PANDORA’S FINANCE - ABLOC CEX - ADEX EXCHANGE - RA WALLET",
  "homeecosystemHeading3": "ABLOC CEX",
  "homeecosystemHeading3text": "Compra, vende y haz trading de cripto activos. Diseñado para la comunidad con excelentes retornos, costos bajos y una interfaz fácil de usar.",
  "homeecosystemHeading4": "ADEX EXCHANGE",
  "homeecosystemHeading4text": "El exchange descentralizado multi-cadena. Controla y administra tus fondos e intercambia activos digitales de manera segura e instantánea, todo con tarifas muy bajas.",
  "homeecosystemHeading1": "DREAMHUB",
  "homeecosystemHeading1text": "Suéñalo, Créalo, Colecciónalo, el mercado NFT para todos los artistas, coleccionistas y soñadores.",
  "homeecosystemHeading2": "PANDORA’S FINANCE",
  "homeecosystemHeading2text": "Utilizando blockchain para fondear ideas, start-ups, empresas y proyectos de bienes raíces ofreciendo oportunidades de inversión a largo plazo.",
  "homeecosystemHeading5": "RA WALLET",
  "homeecosystemHeading5text": "No es solo es otra billetera Defi. El puente entre los activos reales y la blockchain está aquí. Integración de sistemas bancarios, criptomonedas, recompensas y más.",
  "homesectionRoadmap": "ROADMAP ORBITANTE",
  "homesectionRoadmapYear": "2022 - 2023",
  "homesectionSale": "Venta Privada de AGOD",
  "homesectionBuilt": "CONSTRUIDO EN LA RED DE  FANTOM",
  "homesectionBuiltText": "Completamente compatible con EVM (Ethereum Virtual Machine).",
  "homebuiltP1": "Web3JS API y soporte RPC.",
  "homebuiltP2": "Contratos inteligentes construidos con Solidity y Vyper.",
  "homebuiltP3": "Compilado y ejecutado en Ethereum, completamente compatible con la red de Opera.",
  "homesectionCopyright": "Copyright AGOD Ecosystem 2023 by AGOD Ecosystem S.A. de C.V.",
  // "homesectionCopyrightLink": "KNOCKOUT MEDIA.",
  "homesectionTermAndPolicy1": "TÉRMINOS DE USO",
  "homesectionTermAndPolicy2": "POLÍTICA DE PRIVACIDAD",
  "homesectionNav": "Aprende: ",
  "homesectionNav1Link1": "Introducción",
  "homesectionNav1Link2": "Staking",
  "homesectionNav1Link3": "FAQ",
  "homesectionNav1Link4": "RECIBE TRANSMISIONES",
  "homesectionNav1Link5": "Documentación",
  "homesectionNav1Link4placeHolder": "Ingresa tu Email",
  "homesectionExplore": "Ecosistema",
  "homesectionExplore1": "Billetera",
  "homesectionExplore2": "Tokens",
  "comingSoon": "*Próximamente",
  "homesectionExplore3": "Comunidad",
  "homesectionExplore4": "Comunidad",
  "LanguageText": "Cambiar Lenguaje",
  "homeAgodToken":"AGOD",
  "homeAgodTokenText":"EL MOTOR @@ DEL ECOSISTEMA",
  "learnheading1": "PUENTE DE INVERSIÓN @@ SIMPLE E IDEAL ",
  "learnheading1Para": "Los recursos de AGOD se asignan a la @@ comunidad, al Ecosistema, permitiendo que todos los @@ participantes crezcan a medida que el ecosistema @@ crece con ellos. Siendo transparentes sobre @@ cómo se gobierna cada distinto recurso y dando a las @@ personas el poder de votar en nuestra @@ propia comunidad, nuestro propio ecosistema.",
  "learnheading2": "IMPACTO ",
  "learnheading2Para": "Todos podemos aprovechar lo mejor @@ del mundo descentralizado, AGOD te @@ permitirá habilitar fácilmente @@ el uso de tu cuenta bancaria @@ para realizar transacciones. En lugar @@ de tener que utilizar varias funciones o @@ diferentes aplicaciones. La interconectividad de AGOD @@ te brinda una economía de @@ propiedad dentro de todas nuestras funciones, convirtiendo @@ tus beneficios en activos del mundo real.",
  // "learnpara3": "Economía respaldada por el token AGOD. Todos estos @@ servicios están encadenados al @@ Token $AGOD del Ecosistema de AGOD. @@ El proveedor de servicios de conectividad, @@ agregando valor económico, seguridad y @@ brindando sostenibilidad a todos los servicios y @@ activos digitales en el ecosistema. Con inversiones @@ a largo plazo, estabilizando así la tesorería @@ y construyendo las bases para las plataformas @ de todo el ecosistema.",
  "learnpara3": "Las plataformas del Ecosistema @@ están interconectadas al Token $AGOD. @@ Son servicios de conectividad, @@ agregando valor economíco, seguridad y @@ bringando sustentabilidad @@ con activos digitables en el Ecosistema.",
  "learnheading3": "THE &nbsp;&nbsp;&nbsp; AGOD &nbsp;&nbsp;&nbsp; TOKEN",
  "learnheading3Para": "El token AGOD es el token nativo del @@ ecosistema. Con el cual podrán interconectarse y @@ obtener beneficios en toda su economía. @@ AGOD Token asegura todo el @@ ecosistema y las recompensas @@ se distribuyen  entre los Agoders, al @@ realizar staking y tener tarifas de @@ transacción, la economía permite @@ a los usuarios beneficiarse y @@ maximizar  sus inversiones.",
  "learnpara4": "Las plataformas descentralizadas son redes autónomas @@ que benefician y crean valor para @@ todos los usuarios. El Ecosistema @@ AGOD ofrece plataformas descentralizadas @@ y centralizadas para que todos sus usuarios, creadores, artistas e @@ inversores tengan elección; cada plataforma, ofreciendo @@ diferentes tipos de beneficios. Todos los usuarios son @@ libres de elegir beneficiarse de @@ una en específico o de todas, @@ independientemente de su situación económica.",
  "learnheading4": "Valor",
  "learnheading4Para": "El intercambio del Ecosistema permite a los @@ usuarios encontrar coleccionables únicos, no solo @@ intercambiar criptomonedas, también arte digital, NFT’s y @@ más criptoactivos, agregando valor al @@ ecosistema y creando infinitas @@ oportunidades para aquellos @@ dentro del Ecosistema de AGOD.",
  "learnheading5": "MARKETPLACE",
  "learnheading6 ": "Explora",
  "learnpara6": "Descubre el Ecosistema de AGOD",
  "learnpara6P": "Obtén más información sobre las próximas funciones y su evolución a lo largo del tiempo.",
  "learnheading7": "Sobre nosotros",
  "learnpara7": "Descubre más sobre quiénes somos, nuestra visión y lo que queremos lograr.",
  "learnpara7Link": "Sobre nosotros",
  "learnheading8": "Explora",
  "learnheading9": "Recursos",
  "learnpara9": "Encuentra respuestas a tus preguntas sobre el Ecosistema de AGOD.",
  "learnheading10": "FAQ",
  "learnpara10": "AGOD nace como un ecosistema para la comunidad y accesible para todos, @@ busca alentar a los usuarios a explorar el universo cripto, ampliar sus horizontes de @@ inversión y @@ ayudarlos a encontrar otras formas de obtener mayores beneficios en este constante mundo cambiante.",
  "learnpara11": "Ingresa y explora el ecosistema en expansión de AGOD, @@ donde encontrarás ilimitadas posibilidades de inversión listas para aprovecharse.",
  "learnpara12": "Obten AGOD ahora →",


  // "stackingheading1": "Staking ",
  // "stackingheading2": "STAKEAR = ASEGURAR ",
  // "stackingheading3": "EL ECOSISTEMA = GANAR BENEFICIOS",
  // "stackingpara1": "Beneficios",
  // "stackingpara2": "Excelente manera de aumentar tus AGOD tokens @@ Ingresos pasivos sin invertir mucho tiempo @@ Los fondo s se depositan e un contrato inteligente @@ No requiere inversión mínima.",
  // // "stackingpara3.0": "Where do these rewards come from?",
  // "stackingpara3": "Probablemente te estarás preguntando, ¿de dónde vienen estas recompensas?",
  // "stackingpara4": "protocolo de staking que otorga a los poseedores de tokens de AGOD recompensas derivadas de las tarifas de @@ transacción generadas en el ecosistema.",
  // "stackingpara5": "Las tarifas de transacción se cobran a todos los Agoders dentro del ecosistema y luego se distribuyen aL.",
  // "stackingpara6": "través de contratos inteligentes a los titulares de AGOD apostados.",
  // "stackingheading4": "¿ LISTO PARA GANAR RECOMPENSAS",
  // "stackingheading5": "POR HACER STAKING DE TOKENS AGOD ?",
  // "stackingpara7": "ÚNETE A LOS HOLDERS DE AGOD",


  "stackingheading1": "Staking",
  "stackingheading2": "DE AGOD = ASEGURAR",
  "stackingheading3": "EL ECOSISTEMA = GANAR BENEFICIOS",
  "stackingpara1": "Beneficios",
  "stackingpara2": "Excelente manera de aumentar tus AGOD tokens. @@ Ingresos pasivos sin invertir mucho tiempo. @@ Los fondos se depositan en un contrato inteligente. @@ No requiere inversión mínima.",
  "stackingpara3": "¿De dónde vienen estas recompensas?",
  "stackingpara4": "El staking otorga a los poseedores (holders) @@ de tokens AGOD recompensas derivadas de las tarifas de transacción generadas @@ en el ecosistema.",
  "stackingpara5": "Las tarifas de transacción se cobran a todos los Agoders @@ dentro del ecosistema y luego se distribuyen a través de contratos @@ inteligentes a los holders de AGOD staking.",
  "stackingheading4": "¿LISTO PARA GANAR RECOMPENSAS POR",
  "stackingheading5": " HACER STAKING DE TOKENS AGOD?",
  "stackingpara7": "ÚNETE A LOS HOLDERS DE AGOD",



  "faqsline1": "Centro de ayuda",

  "faqsline2": "Preguntas Frecuentes",

  "faqsline3": "Descubre el Ecosistema, Adquiere el conocimiento",
  "faqmore": "Para más información dirígete a nuestra Sección de Preguntas Frecuentes FAQ ",
  "faqsheading1": "¿Qué es una cadena de bloques o blockchain?",
  "faqsheading1Para": "Con un suministro limitado de 200 millones de tokens, también se utilizará para lograr un mayor valor mediante la implementación de un mecanismo de recompra y quema, y se planea reducirlo con el tiempo a 100 millones.",

  "faqsheading2": "¿Qué es AGOD Ecosystem?",
  "faqsheading2Para1": "El Ecosistema AGOD está creado para la comunidad y al alcance de todos, buscando alentar a los usuarios a explorar los beneficios del universo criptográfico y ampliar sus horizontes de inversión, ofreciendo nuevas formas de obtener mayores beneficios en este constante mundo en expansión.",
  "faqsheading2Para2": "Está formado por plataformas blockchain diversificadas, ofreciendo a los usuarios mayores beneficios. Consta de 5 plataformas principales y con un token nativo, el token AGOD. Los usuarios de AGOD podrán interactuar entre todas las plataformas y gozar de grandes recompensas.",
  "faqsheading2Para3": "",

  "faqsheading3": "¿Necesito crear una cuenta en AGOD Ecosystem?",
  "faqsheading3Para": "No, no hay que registrarse o crear una cuenta dentro de AGOD Ecosystem. Puedes comprar y stackear el token AGOD sin ningún tipo de registro.",

  "faqsheading4": "¿Qué es el token AGOD?",
  "faqsheading4Para1": "AGOD es el token nativo del ecosistema. permitiendo a los holders obtener beneficios compartidos por el crecimiento del ecosistema y se utilizará para cubrir las tarifas en todas nuestras plataformas.",
  "faqsheading4Para2": "El suministro inicial de AGOD será de 200 millones, previendo reducirlo con el tiempo a un total de 100 millones, con un sistema de quemado (burning mechanism).",
  "faqsheading4Para3": "La segunda fase de AGOD Ecosystem estará permitiendo realizar staking de AGOD como parte de sus futuras recompensas.",

  "faqheading5": "¿Cómo funciona el token AGOD?",
  // "faqheading5Para1":"AGOD es el token nativo del ecosistema. Los usuarios pueden comprar AGOD y usarlo para interactuar en todas las plataformas, descentralizadas y centralizadas, dentro del ecosistema, funcionando como el token de utilidad, el token principal. Tendremos un suministro total de 100 millones de tokens después de la quema final.",
  "faqheading5Para2": "Una de las mejores características del token AGOD es otorgar recompensas compartidas como beneficio para los holders, obtenidas por parte de la tesorería del Ecosistema, proporcionales a la cantidad de AGOD que posee el usuario. Al tener el mínimo de AGOD, los usuarios podrán obtener una bonificación compartida, proveniente del 20% de los ingresos del Ecosistema.",
  "faqheading5Para3": "La estructura del token AGOD funcionará logrando un mecanismo de quema, realizando recompras trimestrales del mercado secundario y quemando las cantidades compradas. Esto se calculará sobre el rendimiento mensual del ecosistema y los ingresos generales. Creando un entorno sostenible y estabilizando el suministro de AGOD a 100 millones al final del programa de quema.",
  "faqheading5Para4": "Además del beneficio de ganancias compartidas, AGOD Ecosystem ha creado beneficios adicionales para aquellos miembros de la comunidad que creyeron en AGOD desde el prelanzamiento. Los poseedores de AGOD podrán unirse al exclusivo Agoders Club, obteniendo las mejores recompensas y beneficios por holdear AGOD. Obtendran beneficios exclusivos como acceso anticipado a ventas de tokens, nuevos proyectos próximos y mucho más. ¡Cuanto más holdees, más beneficios recibirás!",

  "faqheading6": "¿Cómo puedo comprar AGOD?",
  "faqheading6Para": "¡Prepárate! Pronto podrás comprar tus tokens AGOD a través de nuestro sitio web siguiendo estos sencillos pasos:",
  "faqheading6Ul": [
    "Crear una billetera.",
    "Fondear tu billetera.",
    "Conectar tu billetera a AGOD Ecosystem."
  ],
  "faqheading6link1": "¡Sigue nuestro canal",
  "faqheading6link2": "oficial de Telegram (https://t.me/joinchat/pqK7k1A3rf82NGEx) ",
  "faqheading6link3": "para participar en nuestra venta privada!",

  "faqheading7": "¿Cómo hacer staking de AGOD?",
  "faqheading7Para1": "Próximamente podrás comenzar a ganar recompensas por staking, primero deberás tener el token AGOD. Consulta el proceso de compra si aún no lo tienes. Una vez que tengas el token AGOD en tu billetera, visita ADEX Exchange y selecciona el grupo que está buscando.",
  "faqheading7Para2": "Visita nuestros canales oficiales para mantenerte actualizado sobre noticias, actualizaciones y más",

  "faqheading8": "¿En qué cadena de bloques está integrado el ecosistema AGOD?",
  "faqheading8Para": "AGOD está creado en la red de Fantom para proporcionar tarifas de transacción rápidas, seguras y mínimas a todos nuestros usuarios. Con el objetivo de construir nuestra propia cadena de bloques en el futuro y maximizar los beneficios a todos los holders de AGOD token.Visita nuestros canales oficiales para mantenerte actualizado sobre noticias, actualizaciones y más",

  "faqheading9": "¿AGOD Ecosystem es multicadena (multichain)?",
  "faqheading9Para1": "AGOD comienza como un token de cadena de bloques Fantom que evoluciona hacia un ecosistema multicadena en la siguiente fase inmediata.",
  "faqheading9Para2": "Visita nuestros canales oficiales para mantenerte actualizado sobre noticias, actualizaciones y más.",

  "faqheading10": "¿El ecosistema AGOD tendrá su propia billetera?",
  "faqheading10Para1": "Sí, AGOD Ecosystem tendrá su billetera oficial, utilizada para acceder a tus criptomonedas y todos los proyectos en el Ecosistema, conectándote a cadenas de bloques externas. Podrás almacenar de forma segura tanto tus criptomonedas como tu dinero fiat.",
  "faqheading10Para2": "Visita nuestros canales oficiales para mantenerte actualizado sobre noticias, actualizaciones y más.",

  "faqheading11": " ¿Dónde puedo encontrar más noticias y actualizaciones de las próximas funciones?",
  "faqheading11Para1": "Recuerda, nadie de AGOD Ecosystem te pedirá que envíes fondos o compartas la contraseña de tu billetera o frases secretas.",
  "faqheading11Para2": "Puedes encontrar más noticias y actualizaciones aquí:",




  "line1": "DESCUBRIENDO",
  "line2": "EL ECOSISTEMA AGOD",
  // "line3":"Bienvenido al Ecosistema; AGOD Ecosystem es un universo sencillo pero poderoso conformado de plataformas @@ interconectadas, combinadas con un gran equipo. Dando como resultado un entorno dinámico, rápido y confiable para que @@ usuarios e inversionistas obtengan grandes beneficios dentro de él. Utilizando la tecnología blockchain, todas las transacciones @@ están aseguradas en contratos inteligentes que permiten a los usuarios interactuar con plataformas centralizadas y descentralizadas @@ de varias maneras, ganándose la confianza de millones de usuarios en todo el mundo. @@ Nuestro Ecosistema es una red interconectada de plataformas vinculadas por un token central, AGOD. Construido para @@ impulsar todo el ecosistema. Los usuarios pueden interactuar y ganar recompensas en todas nuestras plataformas.",
  "line3": "Bienvenido AGOD Ecosystem; es un universo sencillo pero poderoso conformado de  plataformas @@ interconectadas, combinadas con un gran equipo. Dando como resultado un entorno dinámico, rápido y confiable para que @@ usuarios e inversionistas obtengan grandes beneficios dentro de él. Utilizando la tecnología blockchain,@@ todas las  transacciones están aseguradas en contratos inteligentes que permiten a los usuarios interactuar con plataformas @@ centralizadas y descentralizadas  de varias maneras, ganándose la confianza de millones de usuarios en todo el mundo.@@ Nuestro Ecosistema es una red interconectada de plataformas vinculadas por un token central, AGOD. Construido para @@ impulsar todo el ecosistema. Los usuarios pueden interactuar y ganar recompensas en todas nuestras plataformas.",
  "line3Res": "Bienvenido AGOD Ecosystem; es un universo sencillo pero poderoso conformado de  plataformas @@ interconectadas, combinadas con un gran equipo. Dando como resultado un entorno dinámico, rápido y confiable para que @@ usuarios e inversionistas obtengan grandes beneficios dentro de él. Utilizando la tecnología blockchain,@@ todas las  transacciones están aseguradas en contratos inteligentes que permiten a los usuarios interactuar con plataformas @@ centralizadas y descentralizadas  de varias maneras, ganándose la confianza de millones de usuarios en todo el mundo.@@ Nuestro Ecosistema es una red interconectada de plataformas vinculadas por un token central, AGOD. Construido para @@ impulsar todo el ecosistema. Los usuarios pueden interactuar y ganar recompensas en todas nuestras plataformas.",
  // "line3": "Welcome to the Ecosystem; AGOD Ecosystem is a simple yet powerful universe of interconnected platforms @@ combined with a great minded team behind it. Resulting in a fast, reliable dynamic environment for @@ users and investors to obtain great benefits from it Utilizing blockchain technology, all transactions  @@ are secured in smart contracts allowing users to engage with centralized and decentralized @@ platforms in various ways, gaining the trust of millions of users worldwide. @@ Our ecosystem is an interconnected network of platforms linked by one core token, AGOD. Built to @@ power the entire ecosystem. Users are able to interact and earn rewards among all platforms within.",


  "line4": "Utilizando la tecnología blockchain, todas las transacciones están aseguradas en contratos inteligentes que permiten a los usuarios interactuar con plataformas centralizadas y descentralizadas de varias maneras, ganándose la confianza de millones de usuarios en todo el mundo.",
  "line5": "Nuestro Ecosistema es una red interconectada de plataformas vinculadas por un token central, AGOD. Construido para impulsar todo el ecosistema. Los usuarios pueden interactuar y ganar recompensas en todas nuestras plataformas.",
  "heandig1": "AGOD Token",
  "heading0": "Abloc Exchange",
  "heading1Para1": "Token nativo del Ecosistema de AGOD. Potenciador de todo el ecosistema. Habilitando beneficios, transacciones y mucho más.",
  // "heading1Link":"Abloc Exchange (http://www.abloc.exchange/)",
  "heading1Link": "http://Abloc.io",
  "heading1LinkText": "Conoce más →",
  "heading1Para2": "Haz trading de criptomonedas como un profesional de manera muy fácil y segura. Encuentre las criptomonedas más populares, compra, vende, gana y construye tu inversión con nosotros.",
  "heading2": "Pandora’s Finance",
  "heading2Para": "Obtén ingresos pasivos de tus inversiones y haz realidad esa idea de negocios. La mejor incubadora en criptomonedas para emprendedores y startups. Respaldado por bienes raíces y ofreciendo recompensas de inversiones en activos del mundo real, convirtiendo activos tradicionales no digitales, en formas digitales utilizando la tecnología blockchain.",
  // "heading2Link":"Dreamhub NFT Marketplace (https://dreamhub.art/)",
  "heading2Link": "https://pandoras.finance/",
  "heading2LinkText": "Conoce más →",
  "headingDreamHub": "Dreamhub NFT Marketplace",
  "headingDreamHubPara": "Mercado NFT divertido, creativo y artístico. Crea y adquiere tu primera colección NFT con nosotros.",
  "headingDreamHubLink": "https://dreamhub.art/",
  "headingDreamHubLinkText": "Conoce más →",
  "heading3": "ADEX",
  "heading3Para": "La plataforma de trading descentralizada del Ecosistema, con su propio token de gobernanza. Intercambia, gana, obtén ingresos y más, en cualquier lugar y a cualquier hora, sin intermediarios ni terceros",
  "heading4": "Ra Wallet",
  "heading4Para": "Billetera nativa del Ecosistema. Sencilla, segura y fácil de manejar. ¡Obtén grandes recompensas al utilizarla!",
  "heading4Link": "Harmony Ark Foundation",
  "heading4LinkText": "Conoce más →",
  // "heading5Para1": "Organización sin fines de lucro dedicada a la protección y preservación del planeta y de los animales que lo habitan.",
  "heading5Para1": "Colaboramos con differentes organizaciones @@ sin fines de lucro dedicades a la protección, @@ preservación y cuidado en sus diferentes sectores",
  "heading5Para3": "Únete y explora el ecosistema en expansión de AGOD Ecosystem, donde las posibilidades de inversión ilimitadas están ahí para aprovecharse.",
  // "head1ng5Link2": "Obtén AGOD ahora ",
  "head1ng5Link2": "Obten AGOD ahora →",


  "getAgodModelHeading": "La venta privada de AGOD Token.",
  "getAgodModelPara1": "Acceso preferencial para inversionistas tempranos. Tendrán el beneficio del comienzo de un protocolo con un ecosistema de grandes expectativas, por lo que su incremento será potencialmente exponencial. ",
  "getAgodModelPara2": "El token está diseñado para ser nativo del ecosistema, al recibir inyección de capital de todos los productos y servicios que AGOD Ecosystem ofrece adquiere un potencial si limite.",
  "getAgodModelPara3": "Un porcentaje de la venta privada, así como de la preventa, se destinará para aportar liquidez y lanzar Abloc Exchange.",

  "connectAWallet":"Conecta Tú Billetera",
  "creditDebit":"Tarjeta de Crédito/Débito",
  "getAgodBottomHeading1":"Un Hogar para tus Activos Digitales",
  "getAgodBottomPara1":"Las billeteras electrónicas son utilizadas para enviar, recibir, almacenar y mostrar activos digitales, tales como Etherium y NFT’s.",
  "getAgodBottomHeading2":"Una Nueva Forma de Iniciar Sesión",
  "getAgodBottomHeadPara2":"En lugar de tener que crear nuevos usuarios y contraseñas en cada sitio web, únicamente conecta tu billetera y listo.",

  "twitterLink": "https://twitter.com/AgodEcosystem",
  "facebookLink": "https://www.facebook.com/agodecosystem",
  "instagramLink": "https://www.instagram.com/agodecosystem/",
  "telegramLink": "https://t.me/joinchat/pqK7k1A3rf82NGEx",
  "linkedInLink": "https://www.linkedin.com/company/agodecosystem",
  "mediumLink": "https://agodecosystem.medium.com/",
  "tiktokLink": "https://www.tiktok.com/@agodecosystem" 

}
module.exports = espContent
